import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:rohittest/appstyle/app_dimensions.dart';

class AppSpacing {
  AppSpacing._();

  static Widget h2 = SizedBox(height: AppDimensions.d2.h);
  static Widget h3 = SizedBox(height: AppDimensions.d3.h);
  static Widget h4 = SizedBox(height: AppDimensions.d4.h);
  static Widget h5 = SizedBox(height: AppDimensions.d5.h);
  static Widget h6 = SizedBox(height: AppDimensions.d6.h);
  static Widget h7 = SizedBox(height: AppDimensions.d7.h);
  static Widget h8 = SizedBox(height: AppDimensions.d8.h);
  static Widget h9 = SizedBox(height: AppDimensions.d9.h);
  static Widget h10 = SizedBox(height: AppDimensions.d10.h);
  static Widget h11 = SizedBox(height: AppDimensions.d11.h);
  static Widget h12 = SizedBox(height: AppDimensions.d12.h);
  static Widget h13 = SizedBox(height: AppDimensions.d13.h);
  static Widget h14 = SizedBox(height: AppDimensions.d14.h);
  static Widget h15 = SizedBox(height: AppDimensions.d15.h);
  static Widget h16 = SizedBox(height: AppDimensions.d16.h);
  static Widget h17 = SizedBox(height: AppDimensions.d17.h);
  static Widget h18 = SizedBox(height: AppDimensions.d18.h);
  static Widget h19 = SizedBox(height: AppDimensions.d19.h);
  static Widget h20 = SizedBox(height: AppDimensions.d20.h);
  static Widget h21 = SizedBox(height: AppDimensions.d21.h);
  static Widget h22 = SizedBox(height: AppDimensions.d22.h);
  static Widget h23 = SizedBox(height: AppDimensions.d23.h);
  static Widget h24 = SizedBox(height: AppDimensions.d24.h);
  static Widget h25 = SizedBox(height: AppDimensions.d25.h);
  static Widget h26 = SizedBox(height: AppDimensions.d26.h);
  static Widget h27 = SizedBox(height: AppDimensions.d27.h);
  static Widget h28 = SizedBox(height: AppDimensions.d28.h);
  static Widget h29 = SizedBox(height: AppDimensions.d29.h);
  static Widget h30 = SizedBox(height: AppDimensions.d30.h);
  static Widget h31 = SizedBox(height: AppDimensions.d31.h);
  static Widget h32 = SizedBox(height: AppDimensions.d32.h);
  static Widget h33 = SizedBox(height: AppDimensions.d33.h);
  static Widget h35 = SizedBox(height: AppDimensions.d35.h);
  static Widget h36 = SizedBox(height: AppDimensions.d36.h);
  static Widget h37 = SizedBox(height: AppDimensions.d37.h);
  static Widget h38 = SizedBox(height: AppDimensions.d38.h);
  static Widget h40 = SizedBox(height: AppDimensions.d40.h);
  static Widget h42 = SizedBox(height: AppDimensions.d40.h);
  static Widget h45 = SizedBox(height: AppDimensions.d45.h);
  static Widget h46 = SizedBox(height: AppDimensions.d46.h);
  static Widget h48 = SizedBox(height: AppDimensions.d48.h);
  static Widget h50 = SizedBox(height: AppDimensions.d50.h);
  static Widget h57 = SizedBox(height: AppDimensions.d57.h);
  static Widget h60 = SizedBox(height: AppDimensions.d60.h);
  static Widget h70 = SizedBox(height: AppDimensions.d70.h);
  static Widget h75 = SizedBox(height: AppDimensions.d75.h);
  static Widget h80 = SizedBox(height: AppDimensions.d80.h);
  static Widget h81 = SizedBox(height: AppDimensions.d81.h);
  static Widget h63 = SizedBox(height: AppDimensions.d63.h);
  static Widget h64 = SizedBox(height: AppDimensions.d64.h);
  static Widget h100 = SizedBox(height: AppDimensions.d100.h);

  static Widget w1 = SizedBox(width: AppDimensions.d1.w);
  static Widget w2 = SizedBox(width: AppDimensions.d2.w);
  static Widget w3 = SizedBox(width: AppDimensions.d3.w);
  static Widget w4 = SizedBox(width: AppDimensions.d4.w);
  static Widget w5 = SizedBox(width: AppDimensions.d5.w);
  static Widget w6 = SizedBox(width: AppDimensions.d6.w);
  static Widget w7 = SizedBox(width: AppDimensions.d7.w);
  static Widget w8 = SizedBox(width: AppDimensions.d8.w);
  static Widget w9 = SizedBox(width: AppDimensions.d9.w);
  static Widget w10 = SizedBox(width: AppDimensions.d10.w);
  static Widget w12 = SizedBox(width: AppDimensions.d12.w);
  static Widget w15 = SizedBox(width: AppDimensions.d15.w);
  static Widget w16 = SizedBox(width: AppDimensions.d16.w);
  static Widget w17 = SizedBox(width: AppDimensions.d17.w);
  static Widget w18 = SizedBox(width: AppDimensions.d18.w);
  static Widget w20 = SizedBox(width: AppDimensions.d20.w);
  static Widget w22 = SizedBox(width: AppDimensions.d22.w);
  static Widget w25 = SizedBox(width: AppDimensions.d25.w);
  static Widget w30 = SizedBox(width: AppDimensions.d30.w);
  static Widget w35 = SizedBox(width: AppDimensions.d35.w);
  static Widget w40 = SizedBox(width: AppDimensions.d40.w);

  static Widget w50 = SizedBox(width: AppDimensions.d50.w);
  static Widget w56 = SizedBox(width: AppDimensions.d56.w);
  static Widget w71 = SizedBox(width: AppDimensions.d71.w);
  static Widget w75 = SizedBox(width: AppDimensions.d75.w);
  static Widget w88 = SizedBox(width: AppDimensions.d88.w);
  static Widget w98 = SizedBox(width: AppDimensions.d98.w);
}